version: "3.8"

networks:
  net:
    name: moviapp_net

volumes:
  moviapp_db:
      driver: local

services:
  postgres:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SPACES_ACCESS_KEY_ID=${SPACES_ACCESS_KEY_ID}
      - SPACES_ACCESS_SECRET=${SPACES_ACCESS_SECRET}
      - SPACES_BUCKET_NAME=${SPACES_BUCKET_NAME}
      - SPACES_ENDPOINT=${SPACES_ENDPOINT}
      - SPACES_REGION=${SPACES_REGION}
    volumes:
      - moviapp_db:/var/lib/postgresql/data
      - ./docker/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"
    networks:
      - net

  api:
    restart: always
    image: ${TAG}
    container_name: subastas_api
    networks:
      - net
    environment:
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}
      BACKEND_URL: ${BACKEND_URL}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      ORIGINS: ${ORIGINS}
      PORT: ${PORT}
      PROXY: ${PROXY}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BACKEND_URL: ${BACKEND_URL}
        DATABASE_URL: ${DATABASE_URL}
        ORIGINS: ${ORIGINS}
        PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
